### ISSUE TITLE
 no member named 'message_text_sensor_' in kilovault_bms_ble.cpp

### ISSUE THREAD

**Issue by KalebClark** [fancygaphtrn/esphome#2]
Hi, I have a dozen of the Kilovault HLX3600+ and I would love to use this for my system especially now that they are discontinuing the app. 

I have downloaded and tried to compile this, and I am getting an error as mentioned in the title. I have looked for the definition of the method message_text_sensor_ and cannot find it, just where it is used in two places in the kilovault_bms_ble.cpp file. Lines 171 and 273. 

Part from the error below:

Any ideas?

`src/esphome/components/kilovault_bms_ble/kilovault_bms_ble.cpp: In member function 'void esphome::kilovault_bms_ble::KilovaultBmsBle::decode_status_data_(const std::vector<unsigned char>&)':
src/esphome/components/kilovault_bms_ble/kilovault_bms_ble.cpp:171:30: error: 'class esphome::kilovault_bms_ble::KilovaultBmsBle' has no member named 'message_text_sensor_'; did you mean 'voltage_sensor_'?
   this->publish_state_(this->message_text_sensor_, format_hex_pretty(&data.front(), 80).c_str());
                              ^~~~~~~~~~~~~~~~~~~~
                              voltage_sensor_
In file included from src/esphome/components/kilovault_bms_ble/kilovault_bms_ble.h:9,
                 from src/esphome/components/kilovault_bms_ble/kilovault_bms_ble.cpp:1:
src/esphome/components/kilovault_bms_ble/kilovault_bms_ble.cpp: In member function 'virtual void esphome::kilovault_bms_ble::KilovaultBmsBle::dump_config()':
src/esphome/components/kilovault_bms_ble/kilovault_bms_ble.cpp:273:40: error: 'class esphome::kilovault_bms_ble::KilovaultBmsBle' has no member named 'message_text_sensor_'; did you mean 'voltage_sensor_'?
   LOG_TEXT_SENSOR("", "Message", this->message_text_sensor_);
                                        ^~~~~~~~~~~~~~~~~~~~
`

**Comment by fancygaphtrn** [comment]
I have updated it recently.  I will post when I get back in town next week.

**Comment by fancygaphtrn** [comment]
updated all the code I am using today for the Kilovault HLX+ batteries I
have.   The files are now in a directory called kilovault and the
integration code in my_components.

It is setup to support 2 batteries per esp32 now.  The entry point is
esp-kiv-bms.yaml, where you will need to update your MAC addresses.

Let me know how it goes.

**Comment by KalebClark** [comment]
It compiled and works! I can see info in debug that is synced to the KV app, so I know its working. I am not familiar with esphome, and not quite sure where this data is trying to go, if anywhere. Good stuff, this is exactly what I need. 

Can I just add more batteries in the config? I have a total of 12.

**Comment by KalebClark** [comment]
OK, I have been working on this most of the day and have a much greater understanding of how this works. I now have my MCU running the code, and reporting to Homeassistant. I can see data from the batteries. This is great! Thank you!

I have been playing with adding more batteries. I know you made this to support two batteries, and if I need to Ill get 6 ESP's to handle my load. But I wanted to experiment with seeing how many batteries I can add. 

First I added two as you had it, and it worked great. I added two more, and I remember it working this morning, but I could be wrong. From there I added two more, then all 12. That took the ESP32 offline. hah... I backed it off to 6, and some of the batteries would not report any data. So I backed it off again to 4. Now, I can't get all four batteries to report. 

When I look at the HASS device the "Controls" section shows all four batteries with the little toggle next to it. One of those at random is off when the ESP starts. Any three work, but not the fourth. If I reboot the ESP, it picks one of the four at random and disables the toggle in the "Controls" section. I have seen all four work at one point, so I can verify that my MAC addresses are correct. 

I have what I have learned today as my experience with esphome & external component development. I have a pretty good grasp of Python, and less confident in C++, but I can usually get around. I have been reading your code to familiarize myself, but I wanted to throw this out to see if you had any thoughts off the top about why that would happen. I would be glad to try to fix myself if I can figure it out, or you could point me in the right direction and submit a PR. 

Thanks,
-Kaleb

**Comment by KalebClark** [comment]
Did some more digging in a different direction. I found in some docs from Expressif that in general, an ESP32 can communicate stably with three devices. Doc is [here](https://docs.espressif.com/projects/esp-faq/en/latest/software-framework/bt/ble.html#what-are-the-risks-if-there-are-over-six-devices-connected-to-esp32-bluetooth-le).

I guess I will go for four ESP's to handle my load of 12 batteries.

**Comment by fancygaphtrn** [comment]
I personally didn't have much luck getting more than two batteries to work
with one esp32. As a matter of fact, when I first started I was doing one
for one because I was running into trouble.

I think the limitation is not necessarily CPU power, but the Bluetooth of
the esp32. On an esp32. The Bluetooth and Wi-Fi share the same antenna and
the OS is doing some kind of sharing.

Also, I'm like you, I'm not much of a coder I can kind of muddle my way
through.

**Comment by KalebClark** [comment]
I only have two unused esp32's around, so I setup both for three batteries, and it seems to be working. Ordered some more to handle the rest. 

Thats what I read on one post, that handling more than three BTLE devices AND WiFi was an issue. That pointed me to the Expressif document that I linked above. 

You did a great job muddling through this! I've been wanting to figure this one out for a while now. Thank you for your work on this!

Ill close this out, since there is no issue any longer. 

Thanks,
-Kaleb
